const express = require("express");
const router = express.Router();
const BrandRoutes = require("./BrandRoutes");
const CategoryRoutes = require("./CategoryRoutes");
const CountryRoutes = require("./CountryRoutes");
const MerchantRoutes = require("./MerchantRoutes");
const PackagingRoutes = require("./PackagingRoutes");
const ProductRoutes = require("./ProductRoutes");
const ProvinceRoutes = require("./ProvinceRoutes");
const PurchaseOrderRoutes = require("./PurchaseOrderRoutes");
const StoreItemRoutes = require("./StoreItemRoutes");
const StoreRoutes = require("./StoreRoutes");
const CityRoutes = require("./CityRoutes");
const PurchaseOrderItemRoutes = require("./PurchaseOrderItemRoutes");
const StaffRoutes = require("./StaffRoutes");

router.get("/ping", (req, res) => res.locals.sendSuccessResponse(res, "pong"));
router.use("/brand", BrandRoutes);
router.use("/category", CategoryRoutes);
router.use("/city", CityRoutes);
router.use("/country", CountryRoutes);
router.use("/merchant", MerchantRoutes);
router.use("/packaging", PackagingRoutes);
router.use("/product", ProductRoutes);
router.use("/province", ProvinceRoutes);
router.use("/purchaseOrder", PurchaseOrderRoutes);
router.use("/purchaseOrderItem", PurchaseOrderItemRoutes);
router.use("/staff", StaffRoutes);
router.use("/storeItem", StoreItemRoutes);
router.use("/store", StoreRoutes);

module.exports = router;
