module.exports = {
  BOX: "box",
  BOTTLE: "bottle",
  CARTON: "carton",
  BAG: "bag",
  PACKET: "packet",
  CAN: "can",
  JAR: "jar",
  TUBE: "tube",
  POUCH: "pouch",
  BARREL: "barrel",
  CRATE: "crate",
  PALLET: "pallet",
  DRUM: "drum",
  SACHET: "sachet",
  BLISTER_PACK: "blister pack",
  BUNDLE: "bundle",
  CASE: "case",
  PACKAGE: "package",
  OTHER: "other",
};
